version: '3'

services:
  ghost:
    image: ghost:1-alpine
    ports:
      - 2368:2368
    environment:
      - database_client: mysql
      - database_connection_database: ghost
  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD: "root"